name: 'XML Format'
description: 'Check XML formatting with xmllint'
inputs:
  xml-file:
    description: 'The source (.xml) file'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.xml-file }}
